version: '3.0'
services:
  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: gastransitie
      POSTGRES_DB: gastransitie
    ports:
      - 5432:5432
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  web:
    build: web
    links:
      - database
    environment:
      DATABASE_NAME: gastransitie
      DATABASE_USER: gastransitie
      DATABASE_PASSWORD: insecure
      GASTRANSITIE_OBJECTSTORE_PASSWORD:
    ports:
      - "8000:8000"
    volumes:
      - ./web/data:/data
      - ./web/app:/app/
      - ./web/deploy:/deploy
    command: >
      bash -c "/deploy/docker-wait.sh \
              && /deploy/docker-migrate.sh \
              && python manage.py runserver 0.0.0.0:8000"

  swaggerui:
    image: amsterdam/oauth2swaggerui
    ports:
      - 8686:8686